[theme]
primaryColor = "#A855F7"         # Roxo Neon dos botões
backgroundColor = "#0B0F19"      # Fundo super escuro premium da imagem
secondaryBackgroundColor = "#161B26" # Fundo das caixas e do menu lateral
textColor = "#FFFFFF"            # Texto totalmente branco
font = "sans serif"

[server]
enableStaticServing = true